hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - ppo_trainer
  - _self_

algorithm:
  adv_estimator: gae

actor_rollout_ref:
  actor:
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
  rollout:
    n: 1
